#You can provide custom settings there
# model_name: "google/gemini-2.0-flash-001"
# prompt_ocr: "Convert this document to markdown and Katex for calculations / maths. Provide the content as it is provided. Don't remove or add anything. Your only role is to provide some formatting and conversion. Don't translate the content. Respond only with the content in markdown format with Katex for maths."
